<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>GuoBuZiLiaoGuanLi</RootNamespace>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon />
    <StartupObject>GuoBuZiLiaoGuanLi.App</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
  </ItemGroup>
</Project>
